/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package test;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static String capitalize(String in) {
        return in.toUpperCase();
    }

    public static void main(String[] args) {
        System.out.println(capitalize(null));
        System.out.println(new App().getGreeting());
    }
}
